name = "movie-site"
compatibility_date = "2026-08-20"
pages_build_output_dir = "out"

[vars]
VITE_SITE_URL = "https://khophim.org"
VITE_VIDEO_CDN_ORIGIN = "https://video.khophim.org"
VITE_BACKBLAZE_BUCKET = "videomeu8"
VITE_PUBLIC_SUPABASE_URL = "https://ceoxbhsdodllziyxmbqr.supabase.co"
VITE_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_Juh45t-R83dfgJI0O4_PQw_iYYoU-yh"
