export const SITE_URL = 'https://khophim.org';

export const seoLandingUrls = [
  { path: '/xem-phim-online', changefreq: 'weekly', priority: '0.94' },
  { path: '/phim-vietsub', changefreq: 'weekly', priority: '0.92' },
  { path: '/phim-thuyet-minh', changefreq: 'weekly', priority: '0.88' },
  { path: '/phim-long-tieng', changefreq: 'weekly', priority: '0.86' },
  { path: '/phim-full-hd', changefreq: 'weekly', priority: '0.88' },
  { path: '/phim-hay', changefreq: 'weekly', priority: '0.90' },
  { path: '/phim-2026', changefreq: 'daily', priority: '0.90' },
  { path: '/phim-2025', changefreq: 'monthly', priority: '0.74' },
  { path: '/phim-2024', changefreq: 'monthly', priority: '0.70' },
  { path: '/phim-4k', changefreq: 'weekly', priority: '0.78' },
  { path: '/phim-hoan-tat', changefreq: 'weekly', priority: '0.86' },
  { path: '/phim-dang-chieu', changefreq: 'daily', priority: '0.88' },
  { path: '/phim-trailer', changefreq: 'daily', priority: '0.82' },

  { path: '/phim-moi-cap-nhat', changefreq: 'daily', priority: '0.95' },
  { path: '/phim-moi-nhat', changefreq: 'daily', priority: '0.95' },
  { path: '/phim-hot-2026', changefreq: 'daily', priority: '0.90' },
  { path: '/phim-sap-chieu', changefreq: 'weekly', priority: '0.78' },

  { path: '/phim-le', changefreq: 'daily', priority: '0.90' },
  { path: '/phim-bo', changefreq: 'daily', priority: '0.90' },
  { path: '/phim-chieu-rap', changefreq: 'daily', priority: '0.88' },
  { path: '/hoat-hinh', changefreq: 'weekly', priority: '0.84' },
  { path: '/tv-shows', changefreq: 'weekly', priority: '0.78' },
  { path: '/anime', changefreq: 'weekly', priority: '0.86' },
  { path: '/my-nam', changefreq: 'weekly', priority: '0.82' },
  { path: '/phim-ma', changefreq: 'weekly', priority: '0.82' },

  { path: '/phim-han-quoc', changefreq: 'daily', priority: '0.88' },
  { path: '/phim-trung-quoc', changefreq: 'daily', priority: '0.88' },
  { path: '/phim-au-my', changefreq: 'daily', priority: '0.86' },
  { path: '/phim-nhat-ban', changefreq: 'weekly', priority: '0.84' },
  { path: '/phim-thai-lan', changefreq: 'weekly', priority: '0.82' },
  { path: '/phim-viet-nam', changefreq: 'weekly', priority: '0.82' },

  { path: '/the-loai/hanh-dong', changefreq: 'weekly', priority: '0.82' },
  { path: '/the-loai/tinh-cam', changefreq: 'weekly', priority: '0.82' },
  { path: '/the-loai/hai-huoc', changefreq: 'weekly', priority: '0.80' },
  { path: '/the-loai/kinh-di', changefreq: 'weekly', priority: '0.80' },
  { path: '/the-loai/co-trang', changefreq: 'weekly', priority: '0.80' },
  { path: '/the-loai/vien-tuong', changefreq: 'weekly', priority: '0.78' },
  { path: '/the-loai/tam-ly', changefreq: 'weekly', priority: '0.78' },
  { path: '/the-loai/phieu-luu', changefreq: 'weekly', priority: '0.76' },
  { path: '/the-loai/hinh-su', changefreq: 'weekly', priority: '0.76' },
  { path: '/the-loai/chien-tranh', changefreq: 'weekly', priority: '0.74' },
  { path: '/the-loai/gia-dinh', changefreq: 'weekly', priority: '0.74' },
  { path: '/the-loai/bi-an', changefreq: 'weekly', priority: '0.74' },
  { path: '/the-loai/vo-thuat', changefreq: 'weekly', priority: '0.74' },
  { path: '/the-loai/than-thoai', changefreq: 'weekly', priority: '0.72' },
  { path: '/the-loai/hoc-duong', changefreq: 'weekly', priority: '0.72' },
  { path: '/the-loai/am-nhac', changefreq: 'weekly', priority: '0.72' },
  { path: '/the-loai/kinh-dien', changefreq: 'weekly', priority: '0.72' },
  { path: '/the-loai/tai-lieu', changefreq: 'weekly', priority: '0.70' },
  { path: '/the-loai/the-thao', changefreq: 'weekly', priority: '0.70' },
  { path: '/the-loai/khoa-hoc', changefreq: 'weekly', priority: '0.70' },
  { path: '/the-loai/chinh-kich', changefreq: 'weekly', priority: '0.70' },

  { path: '/dien-vien', changefreq: 'weekly', priority: '0.76' },
  { path: '/blog', changefreq: 'weekly', priority: '0.76' },
  { path: '/about', changefreq: 'monthly', priority: '0.60' },
  { path: '/policy', changefreq: 'monthly', priority: '0.50' },
];
