create table if not exists public.operations_alert_notifications (
  id bigint generated by default as identity primary key,
  snapshot_id bigint references public.operations_health_snapshots(id) on delete set null,
  severity text not null check (severity in ('warning','critical')),
  fingerprint text not null,
  status text not null check (status in ('pending','sent','failed')),
  provider_message_id text,
  error_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);
create index if not exists operations_alert_fingerprint_created_idx
  on public.operations_alert_notifications(fingerprint, created_at desc);
alter table public.operations_alert_notifications enable row level security;
revoke all on table public.operations_alert_notifications from public, anon, authenticated;
grant all on table public.operations_alert_notifications to service_role;

do $$
begin
  perform cron.unschedule(jobid) from cron.job where jobname='send-operations-alerts-every-15-minutes';
  perform cron.schedule('send-operations-alerts-every-15-minutes','2,17,32,47 * * * *',$cmd$
    select net.http_post(
      url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/operations-health-alert',
      headers := jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||(select decrypted_secret from vault.decrypted_secrets where name='SUPABASE_ANON_KEY' order by created_at desc limit 1),'x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)),
      body := '{}'::jsonb, timeout_milliseconds := 30000
    );
  $cmd$);
end $$;
