create table if not exists public.seo_gsc_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  success boolean not null default false,
  property_uri text not null default 'sc-domain:khophim.org',
  pages_collected integer not null default 0,
  queries_collected integer not null default 0,
  urls_inspected integer not null default 0,
  indexed_urls integer not null default 0,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists seo_gsc_runs_started_idx on public.seo_gsc_runs(started_at desc);

create table if not exists public.seo_search_metrics (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.seo_gsc_runs(id) on delete cascade,
  dimension_type text not null check (dimension_type in ('page','query')),
  dimension_value text not null,
  date_start date not null,
  date_end date not null,
  clicks numeric not null default 0,
  impressions numeric not null default 0,
  ctr numeric not null default 0,
  position numeric not null default 0,
  collected_at timestamptz not null default now()
);

create index if not exists seo_search_metrics_type_impressions_idx
  on public.seo_search_metrics(dimension_type, impressions desc, collected_at desc);
create index if not exists seo_search_metrics_value_idx
  on public.seo_search_metrics(dimension_type, dimension_value, collected_at desc);

create table if not exists public.seo_url_inspections (
  url text primary key,
  movie_id uuid references public.movies(id) on delete set null,
  slug text,
  verdict text,
  coverage_state text,
  indexing_state text,
  robots_txt_state text,
  page_fetch_state text,
  user_canonical text,
  google_canonical text,
  last_crawl_time timestamptz,
  referring_urls jsonb not null default '[]'::jsonb,
  inspected_at timestamptz not null default now(),
  recommendation text,
  priority integer not null default 0,
  raw_result jsonb not null default '{}'::jsonb
);

create index if not exists seo_url_inspections_priority_idx
  on public.seo_url_inspections(priority desc, inspected_at asc);
create index if not exists seo_url_inspections_verdict_idx
  on public.seo_url_inspections(verdict, inspected_at desc);

alter table public.seo_gsc_runs enable row level security;
alter table public.seo_search_metrics enable row level security;
alter table public.seo_url_inspections enable row level security;
revoke all on table public.seo_gsc_runs, public.seo_search_metrics, public.seo_url_inspections from public, anon, authenticated;
grant all on table public.seo_gsc_runs, public.seo_search_metrics, public.seo_url_inspections to service_role;

do $$
begin
  if exists (select 1 from pg_extension where extname='pg_cron')
     and exists (select 1 from pg_extension where extname='pg_net') then
    perform cron.unschedule(jobid) from cron.job where jobname='collect-gsc-seo-feedback-daily';
    perform cron.schedule('collect-gsc-seo-feedback-daily','23 3 * * *',$cmd$
      select net.http_post(
        url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/gsc-seo-feedback',
        headers := jsonb_build_object(
          'Content-Type','application/json',
          'x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)
        ),
        body := '{"inspection_limit":25}'::jsonb,
        timeout_milliseconds := 120000
      );
    $cmd$);
  end if;
end $$;

-- Keep enough history for trend analysis without allowing daily Search Console
-- snapshots to grow forever.
do $$
begin
  if exists (select 1 from pg_extension where extname='pg_cron') then
    perform cron.unschedule(jobid) from cron.job where jobname='cleanup-gsc-seo-history-weekly';
    perform cron.schedule('cleanup-gsc-seo-history-weekly','41 3 * * 0',$cmd$
      delete from public.seo_search_metrics where collected_at < now() - interval '180 days';
      delete from public.seo_gsc_runs where started_at < now() - interval '365 days';
    $cmd$);
  end if;
end $$;

comment on table public.seo_url_inspections is
  'Latest official Google URL Inspection observations. Google alone decides indexing; this table drives automated prioritization and diagnosis.';
