create table if not exists public.operations_health_snapshots (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  status text not null check (status in ('healthy','warning','critical')),
  score integer not null check (score between 0 and 100),
  active_cron_jobs integer not null default 0,
  failed_cron_jobs integer not null default 0,
  stale_cron_jobs integer not null default 0,
  sync_failures_6h integer not null default 0,
  player_errors_1h integer not null default 0,
  unreachable_streams_1h integer not null default 0,
  seo_eligible integer not null default 0,
  seo_ineligible integer not null default 0,
  details jsonb not null default '{}'::jsonb
);
create index if not exists operations_health_checked_idx on public.operations_health_snapshots(checked_at desc);
alter table public.operations_health_snapshots enable row level security;
revoke all on table public.operations_health_snapshots from public, anon, authenticated;
grant all on table public.operations_health_snapshots to service_role;

create or replace function public.capture_operations_health()
returns public.operations_health_snapshots
language plpgsql
security definer
set search_path = public, cron, pg_temp
as $$
declare
  active_jobs integer;
  failed_jobs integer;
  stale_jobs integer;
  sync_failures integer;
  player_errors integer;
  unreachable_streams integer;
  seo_ok integer;
  seo_bad integer;
  calculated_score integer;
  calculated_status text;
  result public.operations_health_snapshots;
begin
  select count(*) into active_jobs from cron.job where active;
  with latest as (
    select j.jobid, j.jobname, j.schedule, r.status, r.start_time
    from cron.job j
    left join lateral (
      select status, start_time from cron.job_run_details d
      where d.jobid=j.jobid order by start_time desc limit 1
    ) r on true where j.active
  )
  select
    count(*) filter (where status='failed'),
    count(*) filter (where (status is null or start_time < now()-interval '2 hours') and schedule !~ '^[0-9]+ [0-9]+ \\* \\* \\*$')
  into failed_jobs, stale_jobs from latest;

  select count(*) into sync_failures from public.sync_logs
  where run_at >= now()-interval '6 hours' and (success is false or coalesce(errors,0)>0);
  select count(*) into player_errors from public.player_error_events where created_at >= now()-interval '1 hour';
  select count(*) into unreachable_streams from public.stream_health_logs
  where checked_at >= now()-interval '1 hour' and coalesce(is_reachable,false)=false;
  select count(*) filter (where eligible_for_index), count(*) filter (where not eligible_for_index)
    into seo_ok, seo_bad from public.movie_seo_quality_status;

  calculated_score := greatest(0, 100 - failed_jobs*20 - stale_jobs*15 - least(sync_failures,10)*3 - least(player_errors,30) - least(unreachable_streams,20));
  calculated_status := case when failed_jobs>0 or stale_jobs>0 or calculated_score<60 then 'critical'
    when sync_failures>2 or player_errors>10 or unreachable_streams>5 or calculated_score<85 then 'warning'
    else 'healthy' end;

  insert into public.operations_health_snapshots(status,score,active_cron_jobs,failed_cron_jobs,stale_cron_jobs,sync_failures_6h,player_errors_1h,unreachable_streams_1h,seo_eligible,seo_ineligible,details)
  values (calculated_status,calculated_score,active_jobs,failed_jobs,stale_jobs,sync_failures,player_errors,unreachable_streams,seo_ok,seo_bad,
    jsonb_build_object('failed_jobs',(select coalesce(jsonb_agg(jobname),'[]'::jsonb) from (select j.jobname from cron.job j join lateral (select status from cron.job_run_details d where d.jobid=j.jobid order by start_time desc limit 1) r on true where j.active and r.status='failed') x)))
  returning * into result;
  return result;
end;
$$;
revoke all on function public.capture_operations_health() from public, anon, authenticated;
grant execute on function public.capture_operations_health() to service_role;

do $$
begin
  perform cron.alter_job((select jobid from cron.job where jobname='cleanup-observability-logs-daily'), command := $cmd$
    delete from public.player_error_events where created_at < now() - interval '30 days';
    delete from public.stream_health_logs where checked_at < now() - interval '14 days';
    delete from public.sync_logs where run_at < now() - interval '45 days';
    delete from public.operations_health_snapshots where checked_at < now() - interval '30 days';
  $cmd$);
  perform cron.unschedule(jobid) from cron.job where jobname='capture-operations-health-every-5-minutes';
  perform cron.schedule('capture-operations-health-every-5-minutes','*/5 * * * *',$cmd$select public.capture_operations_health();$cmd$);
end $$;

select public.capture_operations_health();
