-- Preserve schedules/active flags while replacing secrets embedded in URLs.
-- Every command resolves CRON_SECRET from Vault only at execution time.
select cron.alter_job((select jobid from cron.job where jobname='auto-repair-player-issues-every-10-minutes'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/auto-repair-player-issues?hours=12&limit=4&threshold=2', headers := jsonb_build_object('x-cron-secret', (select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), timeout_milliseconds := 45000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='cobephim-smart-sync'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/sync-cobephim-feed?limit=20&use_cursor=1&cursor_key=cobephim_global_offset', headers := jsonb_build_object('x-cron-secret', (select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), timeout_milliseconds := 120000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='episode-backfill-guard-every-15-minutes'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/episode-backfill-guard?latest_pages=1&latest_limit=12&backfill_pages=1&backfill_limit=4&skip_direct_ophim=1&skip_blvietsub=1&mismatch_repair_limit=0&refresh_caches=0&child_timeout_ms=25000', headers := jsonb_build_object('x-cron-secret', (select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), timeout_milliseconds := 120000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='episode-mismatch-repair-every-15-minutes'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/episode-backfill-guard?mismatch_only=1&mismatch_scan_limit=260&mismatch_repair_limit=4&mismatch_min_displayed=2&mismatch_max_displayed=250&mismatch_severe_only=0&refresh_caches=1&child_timeout_ms=30000', headers := jsonb_build_object('x-cron-secret', (select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), timeout_milliseconds := 180000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='schedule-email-alerts-every-5-minutes'), command := $cmd$select net.http_post(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/schedule-email-alerts', headers := jsonb_build_object('Content-Type','application/json','x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), body := '{}'::jsonb, timeout_milliseconds := 30000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='stream-health-check-every-15-minutes'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/stream-health-check?limit=60&concurrency=3&deactivate_after=5', headers := jsonb_build_object('x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), timeout_milliseconds := 90000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='stream-health-problem-every-15-minutes'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/stream-health-check?queue=problem&limit=40&concurrency=3&deactivate_after=3', headers := jsonb_build_object('x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), timeout_milliseconds := 60000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='stream-health-stale-hourly'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/stream-health-check?queue=stale&limit=40&concurrency=3&deactivate_after=4', headers := jsonb_build_object('x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), timeout_milliseconds := 60000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='stream-health-unchecked-every-15-minutes'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/stream-health-check?queue=unchecked&limit=60&concurrency=3&deactivate_after=4', headers := jsonb_build_object('x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), timeout_milliseconds := 60000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='sync-blvietsub-smart-repair-every-30-minutes'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/sync-blvietsub-feed?repair_existing=1&limit=4&refresh_search=0', headers := jsonb_build_object('x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), timeout_milliseconds := 150000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='sync-cobephim-backup-every-10-minutes'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/sync-cobephim-feed?limit=30&use_cursor=1&cursor_key=cobephim_global_offset', headers := jsonb_build_object('x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), timeout_milliseconds := 150000);$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='sync-ophim-every-5min'), command := $cmd$select net.http_get(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/auto-sync-ophim-episodes', headers := jsonb_build_object('x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)));$cmd$);

select cron.alter_job((select jobid from cron.job where jobname='sync-tmdb-catalog-daily'), command := $cmd$select net.http_post(url := 'https://dzpddbthdeqbkrcjlzap.supabase.co/functions/v1/sync-tmdb-catalog', headers := jsonb_build_object('Content-Type','application/json','x-sync-secret',(select decrypted_secret from vault.decrypted_secrets where name='CRON_SECRET' order by created_at desc limit 1)), body := jsonb_build_object('pages',3,'limit',180,'months',6), timeout_milliseconds := 180000);$cmd$);
