create table if not exists public.seo_query_page_metrics (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.seo_gsc_runs(id) on delete cascade,
  query text not null,
  page text not null,
  date_start date not null,
  date_end date not null,
  clicks numeric not null default 0,
  impressions numeric not null default 0,
  ctr numeric not null default 0,
  position numeric not null default 0,
  collected_at timestamptz not null default now(),
  unique (run_id, query, page)
);

create index if not exists seo_query_page_metrics_opportunity_idx
  on public.seo_query_page_metrics(run_id, impressions desc, position);
create index if not exists seo_query_page_metrics_page_idx
  on public.seo_query_page_metrics(page, collected_at desc);

alter table public.seo_query_page_metrics enable row level security;
revoke all on table public.seo_query_page_metrics from public, anon, authenticated;
grant all on table public.seo_query_page_metrics to service_role;

comment on table public.seo_query_page_metrics is
  'Google Search Console query-to-landing-page observations used to separate branded visibility from real non-brand SEO opportunities.';
