const SITEMAP_URL = 'https://khophim.org/sitemap-movies.xml';

Deno.serve(async (req) => {
  const url = new URL(req.url);

  if (url.searchParams.get('serve') === '1') {
    return Response.redirect(SITEMAP_URL, 302);
  }

  return new Response(JSON.stringify({
    success: true,
    sitemap: SITEMAP_URL,
    message: 'Movie sitemap is generated by sitemap-movies-xml.',
    generated: new Date().toISOString(),
  }), {
    status: 200,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
      'Access-Control-Allow-Origin': '*',
    },
  });
});
